# The configuration for the matrix portion of the bot. The bot's matrix account must already
# be created proiot to running the bot.
matrix:
  # The homeserver URL for the bot. For example, https://matrix.org
  homeserverUrl: "https://t2bot.io"

  # The access token for the bot that authenticates it on the above homeserver.
  accessToken: "YOUR_TOKEN_HERE"

  # The Matrix ID for the bot's account. For example, @voyager:t2bot.io
  userId: "@voyager:t2bot.io"

# The web settings for the bot (serves the graph)
web:
  # The port to run the webserver on
  port: 8184

  # The address to bind to (0.0.0.0 for all interfaces)
  address: '0.0.0.0'

# Advanced settings to control behaviour of the bot
bot:
  # if enabled, the bot will process all node update requests on startup. This is disabled
  # by default to prevent the bot from attempting to use significant resources on startup.
  processNodeUpdatesOnStartup: false

  # If node updates are enabled, which nodes should be updated on startup?
  nodeUpdatesOnStartup:
    rooms: true
    users: true

# Settings for controlling how logging works
logging:
  file: logs/voyager.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5